name: action01

on:
  schedule:
    - cron : 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: |
          curl https://xp.nodis.com.br/same_day_api/api/buildskuhome?domain=petropolis
          curl https://xp.nodis.com.br/same_day_api/api/buildskuhome?domain=novafriburgo
          curl https://xp.nodis.com.br/same_day_api/api/buildskuxmlseller?domain=petropolis&sellerid=5d7f9a047036f903c340e661
          curl https://xp.nodis.com.br/same_day_api/api/buildskuxmlseller?domain=petropolis&sellerid=5fb40efd5b8c5823e12d1b8e
          curl https://xp.nodis.com.br/same_day_api/api/buildskuxmlseller?domain=petropolis&sellerid=5fd3915f51f299fe47fa8e77
          curl https://xp.nodis.com.br/same_day_api/api/buildskuxml?domain=petropolis
          curl https://xp.nodis.com.br/same_day_api/api/buildskuxml?domain=novafriburgo
