name: action01

on:
  schedule:
    - cron : 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        run: |
          curl https://xp.nodis.com.br/same_day_api/api/buildskuhome?domain=petropolis
          curl https://xp.nodis.com.br/same_day_api/api/buildskuhome?domain=novafriburgo
